### ISSUE TITLE
Initialization of the data

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/Hades252#17]
Here we are setting the first element to zero:
https://github.com/dusk-network/Hades252/blob/22fecbcfecafdec0a2ab55c78d362546666d913f/src/hash.rs#L28

We need to set it to `2^(self.perm.t) - 1`, according to appendix E of https://eprint.iacr.org/2019/458.pdf

**Comment by CPerezz** [comment]
We can use the function `two_pow_k` function:
https://github.com/dusk-network/dusk-zerocaf/blob/e9703c12757dfef6e3063aaa6367073630a6ce0c/src/backend/u64/field.rs#L677) of zerocaf in order to implement something similar for `curve25519-dalek::scalar::Scalar;`.
