### ISSUE TITLE
Fix the `hash` function and name it correctly

### ISSUE THREAD

**Issue by ZER0** [dusk-network/Hades252#29]
As per discussion with Dmitry, the current implementation of the `hash` function is not correct; also it should be named `sponge_hash` or something like that, since it's the Sponge function – Poseidon has also a `hash` function for Merkle Tree, see issue #28

**Comment by CPerezz** [comment]
@ZER0 are you going to do this? Since the issue has been open for quite a long time.

Is the current API the correct one? Or we still need to refactor this?

**Comment by CPerezz** [comment]
This no longer applies, since this functionalities have been moved to the `Poseidon252` repo.

Closing this.
