### ISSUE TITLE
Apply `rustfmt` to all sources

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/Hades252#31]

**Comment by CPerezz** [comment]
For those using VSCode and Vim, it's easy to set the rustfmt to run automatically each time you save. 

For vscode: File -> Preferences -> Settings -> Text Editor -> Formatting -> Format on Save
For Vim: Add `let g:rustfmt_autosave = 1` to your `.vimrc`

**Comment by CPerezz** [comment]
I think this can be closed right @vlopes11 ?
