### ISSUE TITLE
Moving to PLONK/master outdated some README values

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/Hades252#42]
Readme.md file mentions several times the `RistrettoScalar Field` which is no longer being used in `master` impl.

Instead, it is using the `Scalar` & `G1Affine` of `dusk-network/Bls12_381` which is what the PLONK repo is currently relying on as a backend.

This info should be updated as well as the parameters that provide values related to the `Fr` group being used in the implementation.

**Comment by vlopes11** [comment]
Agreed. Not only that, but the whole documentation is outdated

**Comment by CPerezz** [comment]
Will you update it as soon as it is migrated to `master`?

**Comment by CPerezz** [comment]
Closed via #48
